### ISSUE TITLE
[Enhancement] Should we enhance verify download with filename contains a substring for dynamic validation

### ISSUE THREAD

**Issue by nhantrantrong** [elaichenkov/cy-verify-downloads#11]
Thank you very much for your great effort to develop this package @elaichenkov . Could you please enhance ability to validate the filename with regex validation? For example in my test, the downloaded file is named with `<downloadedFilename>_DD-mmm-yyyy_hhmmss`. So could you please do an enhancement so that this `verifyDownload` method can validate if the file whose name includes substring exists?

**Example:**
We have a list of download files:
- downloadFile1-25-Feb-2022_011111.txt
- downloadFile2-25-Feb-2022_011133.txt

Then we can validate the downloaded file exist with something like: `verifyDownloadContains('downloadFile2-25-Feb-2022')` with Passed result

Thank you very much

**Comment by elaichenkov** [comment]
Please, let me know if something doesn't work as expected. Also, don't forget to give it a start.

**Comment by nhantrantrong** [comment]
Hi @elaichenkov,
Thank you very much for your great effort, my friend. It works like a charm. I gave it a start already.
Thank you very much

**Comment by anubajaj23** [comment]
Hi @elaichenkov,

Thank you so much for this plugin, but my use case is different , I need to verify text file i.e Download_error_DD_MM_YY"

I can simply do this by using `cy.verifyDownload('.txt', { contains: true });`. 
but the issue is it is pointing to the default downloads folder i.e cypress/Downloads. the same is working without contains but not with contains.

Working Condition -  `cy.verifyDownload('cypress/downloads/My_downloads/test.pdf');`
Not Working Condition -` cy.verifyDownload('cypress/downloads/My_downloads/test.pdf', {contains; true);`

Changing downloads directory is not an option in my case, because downloads are unzipping into My Downloads  folder.

Can you please help me on this ?
