### ISSUE TITLE
isFileExists is on a loop after file is downloaded

### ISSUE THREAD

**Issue by kartikmuchandi** [elaichenkov/cy-verify-downloads#2]
Hi! 
Thanks for this amazing plugin!

However, i am facing an issue. Will describe in brief whats going on.

There is a isFileExist method used in the plugin, which checks for the file at the download location but doesn't register or assert that the file is found.
I physically checked during runtime, File is actually present.
And more over, the isFileExist is in a loop.

![image](https://user-images.githubusercontent.com/71788487/145133977-ad937f4c-38c7-4b0e-8e91-caf53ee8a416.png)

**Comment by elaichenkov** [comment]
Hey,
Thanks for the well-described issue. 

The `isFileExist` function is pretty straightforward, it uses `existsSync` function and that's it. So, I believe that the problem is in the file name or path to the file. Moreover, as I can see in the screenshot there are some differences. It logs that 'Waiting for the `report_12/07/2021.pdf` file' but it tries to find `report_12-08-2021.pdf`. 

```diff
- report_12/07/2021.pdf
+ report_12-08-2021.pdf
```

**Comment by kartikmuchandi** [comment]
Hey, Thanks for pointing it out! And sorry for taking your time for such a small issue...
Thanks again!
